config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:"stories#index"
  resources :stories do
    member do
      put 'like' => 'stories#like'
      put 'unlike' => 'stories#unlike'
      put 'bookmark' => 'stories#bookmark'
      put 'unbookmark' => 'stories#unbookmark'
    end
    resources :comments
  end
  resources :comments, except: [:index, :new] do
    member do
      put 'like' => 'comments#like'
      put 'unlike' => 'comments#unlike'
      put 'bookmark' => 'comments#bookmark'
      put 'unbookmark' => 'comments#unbookmark'
    end
    resources :comments
  end
  post '/tinymce_assets', to: 'stories#upload_image'
  post '/tinymce_assets', to: 'comments#upload_image'
  get 'about' => 'pages#about'
  get 'support' => 'pages#support'
  get 'privacy' => 'pages#privacy'
  get 'terms' => 'pages#terms'
  get 'tags/:id' => 'pages#tag'
  put ':id/follow' => 'pages#follow', as: :follow_user
  put ':id/unfollow' => 'pages#unfollow', as: :unfollow_user
  get ':id/not_found' => 'pages#missing', as: :missing
  get ':id' => 'pages#profile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  mount_uploader :file, ImageUploader

  scope :newest_first, lambda {order("created_at DESC")}

  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
  has_many :likes, as: :likeable
  has_many :comment_likers, through: :likes, source: :user
  has_many :bookmarks, as: :bookmarkable
  has_many :comment_bookmarkers, through: :bookmarks, source: :user

  validates :file, file_size: { less_than: 1.megabytes }
  validates_presence_of :body
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, except: [:create, :upload_image]
  before_action :set_commentable, only: [:create]
  before_action :authenticate_user!, except: [:show]

  def show
  end

  def edit
  end

  def create
    @comment = @commentable.comments.new(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to :back, notice: "Your comment was successfully published!"
    else
      redirect_to :back, notice: "Your comment wasn't published!"
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to @comment, notice: "Your comment was successfully updated!"
    else
      redirect_to @comment, notice: "Your comment wasn't updated!"
    end
  end

  def destroy
    @comment.destroy
    redirect_to root_path, notice: "Your comment was successfully deleted!"
  end

  def like
    Like.create(user_id: current_user.id, likeable_id: @comment.id, likeable_type: "Comment")
    redirect_to :back
  end

  def unlike
    Like.find_by(user_id: current_user.id, likeable_id: @comment.id, likeable_type: "Comment").destroy
    redirect_to :back
  end

  def bookmark
    Bookmark.create(user_id: current_user.id, bookmarkable_id: @comment.id, bookmarkable_type: "Comment")
    redirect_to :back
  end

  def unbookmark
    Bookmark.find_by(user_id: current_user.id, bookmarkable_id: @comment.id, bookmarkable_type: "Comment").destroy
    redirect_to :back
  end

  def upload_image
    image = Comment.create params.permit(:file, :alt, :hint )
    render json: {
      image: {
        url: image.file.url
      }
    }, content_type: "text/html"
  end

  private
  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_commentable
    @commentable = Comment.find(params[:comment_id]) if params[:comment_id]
    @commentable = Story.friendly.find(params[:story_id]) if params[:story_id]
  end

  def comment_params
    params.require(:comment).permit(:body, :alt, :hint, :file)
  end
end

app/views/comments/_comment.html.erb
<li>
  <div class="row">
    <div class="col-md-8 col-md-offset-2 panel">
      <div class="row author">
        <div class="col-md-2">
          <%= image_tag(User.find(comment.user_id).profile_photo.author.url, alt: 'Image', class: 'img-circle') %>
        </div>
        <div class="col-md-10">
          <b><%= link_to User.find(comment.user_id).name, "/#{User.find(comment.user_id).username}" %></b><br />
          <small><%= User.find(comment.user_id).bio %></small><br />
          <%= comment.created_at.strftime('%-b %-d, %Y') %>
        </div>
      </div>
      <%= link_to comment do %>
        <div class="body">
          <%= truncate(comment.body.html_safe, length: 100) %>
        </div>
      <% end %>
      <div class="row">
        <div class="col-md-4">
          <% if user_signed_in? %>
            <% if current_user.liked_comments.include? comment %>
              <%= awesome_link('fa fa-heart', unlike_comment_path(comment), class: "engagement used", method: :put) %>
            <% else %>
              <%= awesome_link('fa fa-heart-o', like_comment_path(comment), class: "engagement", method: :put) %>
            <% end %>
          <% else %>
            <%= awesome_link('fa fa-heart-o engagement', like_comment_path(comment), method: :put) %>
          <% end %>

          <% if comment.comment_likers.count > 0 %>
            <%= comment.comment_likers.count %>
          <% end %>
        </div>
        <div class="col-md-4">
          <i class="engagement fa fa-comment-o" aria-hidden="true"></i>
          <% if comment.comments.count > 0 %>
            <%= comment.comments.count %>
          <% end %>
        </div>
        <div class="col-md-3">
          <% if user_signed_in? %>
            <% if current_user.bookmarked_comments.include? comment %>
              <%= awesome_link('fa fa-bookmark', unbookmark_comment_path(comment), class: "engagement used", method: :put) %>
            <% else %>
              <%= awesome_link('fa fa-bookmark-o', bookmark_comment_path(comment), class: "engagement", method: :put) %>
            <% end %>
          <% else %>
            <%= awesome_link('fa fa-heart-o engagement', bookmark_comment_path(comment), method: :put) %>
          <% end %>

          <% if comment.comment_bookmarkers.count > 0 %>
            <%= comment.comment_bookmarkers.count %>
          <% end %>
        </div>
        <% if user_signed_in? %>
          <div class="col-md-1">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="engagement fa fa-chevron-down" aria-hidden="true"></i></a>
            <ul class="dropdown-menu">
              <% if current_user.id == comment.user_id %>
                <li><%= link_to 'Edit Comment', edit_comment_path(comment) %></li>
              <% else %>
                <li><a href="#">Report Comment</a></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</li>

app/views/comments/edit.html.erb
<%= provide(:page_title, 'Edit Comment') %>

<h1 class="text-center">Editing Comment</h1>

<div class="row">
  <div class="col-md-10 col-md-offset-1 panel panel-default" id="form">
    <%= form_for(@comment) do |f| %>
      <div class="field">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control tinymce', id: "text" %>
      </div>

      <div class="actions">
        <%= f.submit 'Publish', class: 'btn btn-success center-block' %>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/show.html.erb
<% provide(:page_title, 'Comment') %>

<div class="row">
  <div class="col-md-8 col-md-offset-2 panel">
    <div class="row author">
      <div class="col-md-2">
        <%= image_tag(User.find(@comment.user_id).profile_photo.author.url, alt: 'Image', class: 'img-circle') %>
      </div>
      <div class="col-md-10">
        <b><%= link_to User.find(@comment.user_id).name, "/#{User.find(@comment.user_id).username}" %></b><br />
        <small><%= User.find(@comment.user_id).bio %></small><br />
        <%= @comment.created_at.strftime('%-b %-d, %Y') %>
      </div>
    </div>
    <div class="body">
      <%= @comment.body.html_safe %>
    </div>
    <div class="row">
      <div class="col-md-4">
        <% if user_signed_in? %>
          <% if current_user.liked_comments.include? @comment %>
            <%= awesome_link('fa fa-heart', unlike_comment_path(@comment), class: "engagement used", method: :put) %>
          <% else %>
            <%= awesome_link('fa fa-heart-o', like_comment_path(@comment), class: "engagement", method: :put) %>
          <% end %>
        <% else %>
          <%= awesome_link('fa fa-heart-o engagement', like_comment_path(@comment), method: :put) %>
        <% end %>

        <% if @comment.comment_likers.count > 0 %>
          <%= @comment.comment_likers.count %>
        <% end %>
      </div>
      <div class="col-md-4">
        <i class="engagement fa fa-comment-o" aria-hidden="true"></i>
        <% if @comment.comments.count > 0 %>
          <%= @comment.comments.count %>
        <% end %>
      </div>
      <div class="col-md-3">
        <% if user_signed_in? %>
          <% if current_user.bookmarked_comments.include? @comment %>
            <%= awesome_link('fa fa-bookmark', unbookmark_comment_path(@comment), class: "engagement used", method: :put) %>
          <% else %>
            <%= awesome_link('fa fa-bookmark-o', bookmark_comment_path(@comment), class: "engagement", method: :put) %>
          <% end %>
        <% else %>
          <%= awesome_link('fa fa-heart-o engagement', bookmark_comment_path(@comment), method: :put) %>
        <% end %>

        <% if @comment.comment_bookmarkers.count > 0 %>
          <%= @comment.comment_bookmarkers.count %>
        <% end %>
      </div>
      <% if user_signed_in? %>
        <div class="col-md-1">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="engagement fa fa-chevron-down" aria-hidden="true"></i></a>
          <ul class="dropdown-menu">
            <% if current_user.id == @comment.user_id %>
              <li><%= link_to 'Edit Comment', edit_comment_path(@comment) %></li>
              <li><%= link_to "Delete Comment", comment_path(@comment), method: :delete, data: { confirm: "Are you sure?" } %></li>
            <% else %>
              <li><a href="#">Report Comment</a></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
</div>
<h2 class="text-center">Responses</h2>
<div class="row">
  <div class="col-md-8 col-md-offset-2 panel panel-default" id="form">
    <%= form_for [@comment, Comment.new] do |f| %>
      <div class="field">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control tinymce' %>
      </div>

      <div class="actions">
        <%= f.submit 'Publish', class: 'btn btn-success center-block' %>
      </div>
    <% end %>
  </div>
</div>
<ul>
  <%= render(partial: 'comments/comment', collection: @comment.comments) %>
</ul>