config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:"stories#index"
  resources :stories do
    member do
      put 'like' => 'stories#like'
      put 'unlike' => 'stories#unlike'
      put 'bookmark' => 'stories#bookmark'
      put 'unbookmark' => 'stories#unbookmark'
    end
    resources :comments
  end
  resources :comments, except: [:index, :new] do
    member do
      put 'like' => 'comments#like'
      put 'unlike' => 'comments#unlike'
      put 'bookmark' => 'comments#bookmark'
      put 'unbookmark' => 'comments#unbookmark'
    end
    resources :comments
  end
  post '/tinymce_assets', to: 'stories#upload_image'
  post '/tinymce_assets', to: 'comments#upload_image'
  get 'about' => 'pages#about'
  get 'support' => 'pages#support'
  get 'privacy' => 'pages#privacy'
  get 'terms' => 'pages#terms'
  get 'tags/:id' => 'pages#tag'
  put ':id/follow' => 'pages#follow', as: :follow_user
  put ':id/unfollow' => 'pages#unfollow', as: :unfollow_user
  get ':id/not_found' => 'pages#missing', as: :missing
  get ':id' => 'pages#profile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/story.rb
class Story < ApplicationRecord
  mount_uploader :banner_image, BannerImageUploader
  mount_uploader :file, ImageUploader

  acts_as_taggable

  belongs_to :user
  has_many :comments, as: :commentable
  has_many :likes, as: :likeable
  has_many :story_likers, :through => :likes, :source => :user
  has_many :bookmarks, as: :bookmarkable
  has_many :story_bookmarkers, :through => :bookmarks, :source => :user

  scope :newest_first, lambda {order("created_at DESC")}
  scope :with_tag, -> (tag) { tagged_with(tag) if tag.present? }
  scope :following_stories, -> (following) {where user_id: following}

  validates_presence_of :title, :message => "is required."
  validates_presence_of :banner_image, on: :create, :message => "is required."
  validates :banner_image, file_size: { less_than: 1.megabytes }
  validates :file, file_size: { less_than: 1.megabytes }
  validates_presence_of :body, :message => "is required."

  extend FriendlyId
  friendly_id :title, use: :slugged

  def should_generate_new_friendly_id?
    title_changed?
  end

  def normalize_friendly_id(string)
    super[0..99]
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_action :set_story, except: [:index, :new, :create, :upload_image]
  before_action :authenticate_user!, except: [:show]

  def index
    @stories = (Story.following_stories current_user.following).newest_first
  end

  def show
  end

  def new
    @story = current_user.stories.new
  end

  def edit
  end

  def create
    @story = current_user.stories.new(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: "Your story was successfully published!" }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new, notice: "Your story wasn't published!" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: "Your story was successfully updated!" }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit, notice: "Your story wasn't updated!" }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  def like
    Like.create(user_id: current_user.id, likeable_id: @story.id, likeable_type: "Story")
    redirect_to @story
  end

  def unlike
    Like.find_by(user_id: current_user.id, likeable_id: @story.id, likeable_type: "Story").destroy
    redirect_to @story
  end

  def bookmark
    Bookmark.create(user_id: current_user.id, bookmarkable_id: @story.id, bookmarkable_type: "Story")
    redirect_to @story
  end

  def unbookmark
    Bookmark.find_by(user_id: current_user.id, bookmarkable_id: @story.id, bookmarkable_type: "Story").destroy
    redirect_to @story
  end

  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: "Your story was successfully deleted!" }
      format.json { head :no_content }
    end
  end

  def upload_image
    image = Story.create params.permit(:file, :alt, :hint )
    render json: {
      image: {
        url: image.file.url
      }
    }, content_type: "text/html"
  end

  private
    def set_story
      @story = Story.friendly.find(params[:id])
    end

    def story_params
      params.require(:story).permit(:title, :banner_image, :file, :alt, :hint, :body, :tag_list)
    end
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/stories/_form.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1 panel panel-default" id="form">
    <%= form_for(story, validate: true) do |f| %>
      <% if story.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(story.errors.count, "error") %> prohibited this post from being saved:</h2>
          <ul>
            <% story.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="field">
        <% if @story.banner_image? && @story.banner_image.size < 1.megabytes %>
          <%= f.label :current_banner_image %><br />
          <%= image_tag(@story.banner_image.medium.url, alt: 'Image') %><br />
          <%= f.label :replace_current_banner_image %>
        <% else %>
          <%= f.label :banner_image %>
        <% end %>
        <%= f.file_field :banner_image, class: 'form-control' %>
      </div>

      <div class="field">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control tinymce', id: "text" %>
      </div>

      <div class="field">
        <%= f.label :tags %>
        <%= f.text_field :tag_list, class: 'form-control', placeholder: "Separate by commas" %>
      </div>

      <div class="actions">
        <%= f.submit 'Publish', class: 'btn btn-success center-block' %>
      </div>
    <% end %>
  </div>
</div>

app/views/stories/edit.html.erb
<%= provide(:page_title, 'Edit Story') %>

<h1 class="text-center">Editing Story</h1>

<%= render 'form', story: @story %>

app/views/stories/index.html.erb
<%= provide(:page_title, 'Medium – a place to read and write big ideas and important stories') %>

<div class="container">
  <div class="row">
    <% @stories.each do |story| %>
      <div class="panel col-md-6 col-md-offset-3">
        <div class="row author">
          <div class="col-md-2">
            <%= image_tag(User.find(story.user_id).profile_photo.author.url, alt: 'Image', class: 'img-circle') %>
          </div>
          <div class="col-md-10">
            <b><%= link_to User.find(story.user_id).name, "/#{User.find(story.user_id).username}" %></b><br />
            <%= story.created_at.strftime('%-b %-d, %Y') %>
          </div>
        </div>
        <%= link_to story do %>
          <div class="read">
            <%= image_tag(story.banner_image.medium.url, alt: 'Image') %>
            <h2 class="text-center"><b><%= story.title %></b></h2>
          </div>
        <% end %>
        <div class="row">
          <div class="col-md-4">
            <% if user_signed_in? %>
              <% if current_user.liked_stories.include? story %>
                <i class="engagement fa fa-heart used" aria-hidden="true"></i>
              <% else %>
                <i class="engagement fa fa-heart-o" aria-hidden="true"></i>
              <% end %>
            <% else %>
              <i class="engagement fa fa-heart-o" aria-hidden="true"></i>
            <% end %>

            <% if story.story_likers.count > 0 %>
              <%= story.story_likers.count %>
            <% end %>
          </div>
          <div class="col-md-4">
            <i class="engagement fa fa-comment-o" aria-hidden="true"></i>
            <% if story.comments.count > 0 %>
              <%= story.comments.count %>
            <% end %>
          </div>
          <div class="col-md-3">
            <% if user_signed_in? %>
              <% if current_user.bookmarked_stories.include? story %>
                <i class="engagement fa fa-bookmark used" aria-hidden="true"></i>
              <% else %>
                <i class="engagement fa fa-bookmark-o" aria-hidden="true"></i>
              <% end %>
            <% else %>
              <i class="engagement fa fa-bookmark-o" aria-hidden="true"></i>
            <% end %>

            <% if story.story_bookmarkers.count > 0 %>
              <%= story.story_bookmarkers.count %>
            <% end %>
          </div>
          <% if user_signed_in? && current_user.id == story.user_id %>
            <div class="col-md-1">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="engagement fa fa-chevron-down" aria-hidden="true"></i></a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Edit Story', edit_story_path(story) %></li>
              </ul>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/stories/new.html.erb
<% provide(:page_title, 'New Story') %>

<h1 class="text-center">New Story</h1>

<%= render 'form', story: @story %>

app/views/stories/show.html.erb
<% provide(:page_title, @story.title) %>

<div class="row">
  <div class="col-md-8 col-md-offset-2 panel">
    <div class="row author">
      <div class="col-md-2">
        <%= image_tag(User.find(@story.user_id).profile_photo.author.url, alt: 'Image', class: 'img-circle') %>
      </div>
      <div class="col-md-10">
        <b><%= link_to User.find(@story.user_id).name, "/#{User.find(@story.user_id).username}" %></b><br />
        <small><%= User.find(@story.user_id).bio %></small><br />
        <%= @story.created_at.strftime('%-b %-d, %Y') %>
      </div>
    </div>
    <h2 class="text-center"><b><%= @story.title %></b></h2>
    <div class="body">
      <%= @story.body.html_safe %>
    </div>
    <div class="tags">
      <p><%= raw @story.tags.map { |t| link_to t.name, "/tags/#{t.name}", class: "btn btn-primary" }.join(' ') %></p>
    </div>
    <div class="row">
      <div class="col-md-4">
        <% if user_signed_in? %>
          <% if current_user.liked_stories.include? @story %>
            <%= awesome_link('fa fa-heart', unlike_story_path(@story), class: "engagement used", method: :put) %>
          <% else %>
            <%= awesome_link('fa fa-heart-o', like_story_path(@story), class: "engagement", method: :put) %>
          <% end %>
        <% else %>
          <%= awesome_link('fa fa-heart-o engagement', like_story_path(@story), method: :put) %>
        <% end %>

        <% if @story.story_likers.count > 0 %>
          <%= @story.story_likers.count %>
        <% end %>
      </div>
      <div class="col-md-4">
        <i class="engagement fa fa-comment-o" aria-hidden="true"></i>
        <% if @story.comments.count > 0 %>
          <%= @story.comments.count %>
        <% end %>
      </div>
      <div class="col-md-3">
        <% if user_signed_in? %>
          <% if current_user.bookmarked_stories.include? @story %>
            <%= awesome_link('fa fa-bookmark', unbookmark_story_path(@story), class: "engagement used", method: :put) %>
          <% else %>
            <%= awesome_link('fa fa-bookmark-o', bookmark_story_path(@story), class: "engagement", method: :put) %>
          <% end %>
        <% else %>
          <%= awesome_link('fa fa-heart-o engagement', bookmark_story_path(@story), method: :put) %>
        <% end %>

        <% if @story.story_bookmarkers.count > 0 %>
          <%= @story.story_bookmarkers.count %>
        <% end %>
      </div>
      <% if user_signed_in? %>
        <div class="col-md-1">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="engagement fa fa-chevron-down" aria-hidden="true"></i></a>
          <ul class="dropdown-menu">
            <% if current_user.id == @story.user_id %>
              <li><%= link_to 'Edit Story', edit_story_path(@story) %></li>
              <li><%= link_to "Delete Story", story_path(@story), method: :delete, data: { confirm: "Are you sure?" } %></li>
            <% else %>
              <li><a href="#">Report Story</a></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
</div>
<h2 class="text-center">Responses</h2>
<div class="row">
  <div class="col-md-8 col-md-offset-2 panel panel-default" id="form">
    <%= form_for [@story, Comment.new] do |f| %>
      <div class="field">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control tinymce' %>
      </div>

      <div class="actions">
        <%= f.submit 'Publish', class: 'btn btn-success center-block' %>
      </div>
    <% end %>
  </div>
</div>
<ul>
  <%= render(partial: 'comments/comment', collection: @story.comments) %>
</ul>