config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to:"stories#index"
  resources :stories do
    member do
      put 'like' => 'stories#like'
      put 'unlike' => 'stories#unlike'
      put 'bookmark' => 'stories#bookmark'
      put 'unbookmark' => 'stories#unbookmark'
    end
    resources :comments
  end
  resources :comments, except: [:index, :new] do
    member do
      put 'like' => 'comments#like'
      put 'unlike' => 'comments#unlike'
      put 'bookmark' => 'comments#bookmark'
      put 'unbookmark' => 'comments#unbookmark'
    end
    resources :comments
  end
  post '/tinymce_assets', to: 'stories#upload_image'
  post '/tinymce_assets', to: 'comments#upload_image'
  get 'about' => 'pages#about'
  get 'support' => 'pages#support'
  get 'privacy' => 'pages#privacy'
  get 'terms' => 'pages#terms'
  get 'tags/:id' => 'pages#tag'
  put ':id/follow' => 'pages#follow', as: :follow_user
  put ':id/unfollow' => 'pages#unfollow', as: :unfollow_user
  get ':id/not_found' => 'pages#missing', as: :missing
  get ':id' => 'pages#profile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-static-top" id="top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
        <span class="icon-bar"></span>
			</button>
      <%= link_to (raw('<b>Medium</b>')), root_path, class: 'navbar-brand' %>
		</div>
		<% if user_signed_in? %>
			<div class="collapse navbar-collapse" id="myNavbar">
				<ul class="nav navbar-nav navbar-right">
					<% if !(yield(:page_title) == ('New Story') || yield(:page_title) == ('Edit Story')) %>
						<li><%= link_to 'New Story', new_story_path %></li>
					<% end %>
					<li><a href="#"><i class="fa fa-bell-o" aria-hidden="true"></i></a></li>
					<li class="dropdown">
						<a class="dropdown-toggle" data-toggle="dropdown" href="#"><%= image_tag(current_user.profile_photo.navbar.url, alt: 'Image', class: 'img-circle') %></a>
						<ul class="dropdown-menu">
							<li><%= link_to 'Profile', "/#{current_user.username}" %></li>
							<li><%= link_to 'Settings', edit_user_registration_path %></li>
							<li role="separator" class="divider"></li>
							<li><%= link_to 'About', about_path %></li>
							<li><%= link_to 'Support', support_path %></li>
							<li><%= link_to 'Privacy', privacy_path %></li>
							<li><%= link_to 'Terms', terms_path %></li>
							<li role="separator" class="divider"></li>
							<li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
						</ul>
					</li>
				</ul>
				<form class="navbar-form" role="search" id="search">
					<div class="form-group">
						<input type="text" class="form-control text-center" placeholder="Search" id="query">
					</div>
				</form>
			</div>
		<% end %>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %></title>
    <%= favicon_link_tag asset_path('favicon.png'), :rel => 'icon', :type =>  'image/png' %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Droid+Serif" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container main">
		  <% if flash.any? %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>